// The closed-alpha welcome bulletin (shared/welcome-notice.js).
//
// Everything it shows comes from /data/changelog.json, generated by
// Scripts/changelog.ps1. These tests drive the module against fixtures by
// stubbing fetch, so they assert the render and the fail-closed path without
// depending on whatever release happens to be checked in.
//
// The module caches the fetched document in a closure, so each test installs its
// fixture BEFORE the first call and the page reloads between harness cases.

const FIXTURE = {
    releases: [
        {
            version: '2.0.1', channel: 'Alpha', sha: 'aaa1111', date: '2026-08-28',
            title: 'A quieter night',
            entries: [
                { type: 'added', scope: 'Menus', text: 'The setup screen has a volume slider.' },
                { type: 'fixed', scope: 'Co-op', text: 'Craft orders go through.' },
            ],
            known_issues: [
                { scope: 'Store', ref: 330, text: 'Furniture near stairs spawns floating.' },
            ],
        },
        {
            version: null, channel: 'Alpha', sha: 'bbb2222', date: '2026-08-15',
            title: 'Fifty-two fixes',
            entries: [{ type: 'fixed', scope: 'Saves', text: 'Reading a note no longer eats it.' }],
            known_issues: [],
        },
    ],
};

// The harness exposes the iframe document; its defaultView is the page window,
// which is the same route test-harness.js itself uses to reach it.
function stubFetch(ctx, responder) {
    ctx.doc.defaultView.fetch = (url) => Promise.resolve(responder(url));
}

const okJson = (body) => ({ ok: true, status: 200, json: () => Promise.resolve(body) });

TSICTestHarness.register({
    name: 'Welcome notice: renders every release from the changelog',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson(FIXTURE));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        const titles = Array.from(ctx.doc.querySelectorAll('.wn-entry-title')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(titles.length, 2, 'expected one block per release'));
        ctx.expect(ctx.assert.eq(titles[0], 'A quieter night'));
        ctx.expect(ctx.assert.eq(titles[1], 'Fifty-two fixes'));

        const items = Array.from(ctx.doc.querySelectorAll('.wn-entry li')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(items.length, 3, 'expected every entry across both releases'));
        ctx.expect(ctx.assert.eq(items[0], 'The setup screen has a volume slider.'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: masthead reads channel + version, and the SHA is the seen-flag',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson(FIXTURE));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        ctx.expect(ctx.assert.eq(
            ctx.doc.querySelector('.tsic-masthead-date').textContent,
            'Alpha 2.0.1 · 28 Aug 2026'));

        // The identity is the SHA, never the version: a forgotten version bump
        // must not silently re-show or suppress the bulletin.
        ctx.expect(ctx.assert.eq(ctx.doc.defaultView.TSIC.WelcomeNotice.noticeVersion(), 'aaa1111'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: a release with no version falls back to its build SHA',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        // Backfilled builds predate the versioning scheme and carry version: null.
        stubFetch(ctx, () => okJson({ releases: [FIXTURE.releases[1]] }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        ctx.expect(ctx.assert.eq(
            ctx.doc.querySelector('.tsic-masthead-date').textContent,
            'Build bbb2222 · 15 Aug 2026'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: known issues render with scope and ref',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson(FIXTURE));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        const rows = ctx.doc.querySelectorAll('.wn-issue');
        ctx.expect(ctx.assert.eq(rows.length, 1, 'only the newest release supplies known issues'));
        ctx.expect(ctx.assert.eq(rows[0].querySelector('.wn-issue-tag').textContent, 'Store'));
        ctx.expect(ctx.assert.eq(rows[0].querySelector('.wn-issue-ref').textContent, '#330'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: internal entries never reach the bulletin',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson({
            releases: [{
                version: '2.0.2', channel: 'Alpha', sha: 'ccc3333', date: '2026-08-28',
                title: 'Internal check',
                entries: [
                    { type: 'fixed', scope: 'Store', text: 'A thing a player can see.' },
                    { type: 'changed', scope: 'Build', text: 'A thing only we care about.', internal: true },
                ],
                known_issues: [],
            }],
        }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        const items = Array.from(ctx.doc.querySelectorAll('.wn-entry li')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(items.length, 1, 'the internal entry is filtered out'));
        ctx.expect(ctx.assert.eq(items[0], 'A thing a player can see.'));
    },
});

// Fail-closed. A missing changelog is not the player's problem, and the menu
// behind the bulletin still has to work.
TSICTestHarness.register({
    name: 'Welcome notice: a missing changelog mounts nothing',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => ({ ok: false, status: 404, json: () => Promise.resolve(null) }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.mount({ waitMs: 20 });
        await new Promise(r => setTimeout(r, 60));

        ctx.expect(ctx.assert.falsy(ctx.doc.getElementById('welcome-notice'),
            'no bulletin should be built when the fetch fails'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: an empty release list mounts nothing',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson({ releases: [] }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.mount({ waitMs: 20 });
        await new Promise(r => setTimeout(r, 60));

        ctx.expect(ctx.assert.falsy(ctx.doc.getElementById('welcome-notice'),
            'a changelog with no releases is as good as no changelog'));
    },
});
