// The closed-alpha welcome bulletin (shared/welcome-notice.js).
//
// Everything it shows comes from /data/changelog.json, generated by
// Scripts/changelog.ps1. These tests drive the module against fixtures by
// stubbing fetch, so they assert the render and the fail-closed path without
// depending on whatever release happens to be checked in.
//
// The module caches the fetched document in a closure, so each test installs its
// fixture BEFORE the first call and the page reloads between harness cases.

const FIXTURE = {
    releases: [
        {
            version: '2.0.1', channel: 'Alpha', sha: 'aaa1111', date: '2026-08-28',
            title: 'A quieter night',
            entries: [
                { type: 'added', scope: 'Menus', text: 'The setup screen has a volume slider.' },
                { type: 'fixed', scope: 'Co-op', text: 'Craft orders go through.' },
            ],
            known_issues: [
                { scope: 'Store', ref: 330, text: 'Furniture near stairs spawns floating.' },
            ],
        },
        {
            version: null, channel: 'Alpha', sha: 'bbb2222', date: '2026-08-15',
            title: 'Fifty-two fixes',
            entries: [{ type: 'fixed', scope: 'Saves', text: 'Reading a note no longer eats it.' }],
            known_issues: [],
        },
    ],
};

// The harness exposes the iframe document; its defaultView is the page window,
// which is the same route test-harness.js itself uses to reach it.
function stubFetch(ctx, responder) {
    ctx.doc.defaultView.fetch = (url) => Promise.resolve(responder(url));
}

const okJson = (body) => ({ ok: true, status: 200, json: () => Promise.resolve(body) });

TSICTestHarness.register({
    name: 'Welcome notice: renders every release from the changelog',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson(FIXTURE));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        const titles = Array.from(ctx.doc.querySelectorAll('.wn-entry-title')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(titles.length, 2, 'expected one block per release'));
        ctx.expect(ctx.assert.eq(titles[0], 'A quieter night'));
        ctx.expect(ctx.assert.eq(titles[1], 'Fifty-two fixes'));

        const items = Array.from(ctx.doc.querySelectorAll('.wn-entry li')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(items.length, 3, 'expected every entry across both releases'));
        ctx.expect(ctx.assert.eq(items[0], 'The setup screen has a volume slider.'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: masthead reads channel + version, and the name is the seen-flag',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson(FIXTURE));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        ctx.expect(ctx.assert.eq(
            ctx.doc.querySelector('.tsic-masthead-date').textContent,
            'Alpha 2.0.1 · 28 Aug 2026'));

        // The identity is the release NAME, not the SHA: the recorded SHA is
        // stamped at cut time and re-stamped by every amend, so keying on it
        // re-showed the bulletin for rebuilds with nothing new in them.
        ctx.expect(ctx.assert.eq(
            ctx.doc.defaultView.TSIC.WelcomeNotice.noticeVersion(), 'Alpha 2.0.1'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: the seen-flag survives a re-stamped SHA',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        // The same release, amended: new SHA, new date, same version. A player
        // who has seen it must not be shown it again - this is the whole reason
        // the identity moved off the SHA.
        const amended = JSON.parse(JSON.stringify(FIXTURE));
        amended.releases[0].sha = 'zzz9999';
        amended.releases[0].date = '2026-09-01';
        stubFetch(ctx, () => okJson(amended));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        ctx.expect(ctx.assert.eq(
            ctx.doc.defaultView.TSIC.WelcomeNotice.noticeVersion(), 'Alpha 2.0.1'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: a release with no version falls back to its build SHA',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        // Backfilled builds predate the versioning scheme and carry version: null.
        stubFetch(ctx, () => okJson({ releases: [FIXTURE.releases[1]] }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        ctx.expect(ctx.assert.eq(
            ctx.doc.querySelector('.tsic-masthead-date').textContent,
            'Build bbb2222 · 15 Aug 2026'));

        // With no version there is nothing else to key on, so the identity is
        // still the SHA for these - the one case the old behaviour survives.
        ctx.expect(ctx.assert.eq(
            ctx.doc.defaultView.TSIC.WelcomeNotice.noticeVersion(), 'Build bbb2222'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: known issues render with scope and ref',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson(FIXTURE));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        const rows = ctx.doc.querySelectorAll('.wn-issue');
        ctx.expect(ctx.assert.eq(rows.length, 1, 'only the newest release supplies known issues'));
        ctx.expect(ctx.assert.eq(rows[0].querySelector('.wn-issue-tag').textContent, 'Store'));
        ctx.expect(ctx.assert.eq(rows[0].querySelector('.wn-issue-ref').textContent, '#330'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: internal entries never reach the bulletin',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson({
            releases: [{
                version: '2.0.2', channel: 'Alpha', sha: 'ccc3333', date: '2026-08-28',
                title: 'Internal check',
                entries: [
                    { type: 'fixed', scope: 'Store', text: 'A thing a player can see.' },
                    { type: 'changed', scope: 'Build', text: 'A thing only we care about.', internal: true },
                ],
                known_issues: [],
            }],
        }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        const items = Array.from(ctx.doc.querySelectorAll('.wn-entry li')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(items.length, 1, 'the internal entry is filtered out'));
        ctx.expect(ctx.assert.eq(items[0], 'A thing a player can see.'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: groups by category, then by scope, in reading order',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        // Deliberately out of order and with a scope split across the list: a frozen
        // release keeps the order its entries were authored in, so the bulletin has
        // to do the grouping rather than trust the file.
        stubFetch(ctx, () => okJson({
            releases: [{
                version: '2.0.3', channel: 'Alpha', sha: 'ddd4444', date: '2026-08-28',
                title: 'Grouping check',
                entries: [
                    { type: 'fixed',   scope: 'Menus', text: 'Fixed the first menu thing.' },
                    { type: 'added',   scope: 'Store', text: 'Added a store thing.' },
                    { type: 'fixed',   scope: 'Co-op', text: 'Fixed a co-op thing.' },
                    { type: 'changed', scope: 'Menus', text: 'Changed a menu thing, so it reads better.' },
                    { type: 'fixed',   scope: 'Menus', text: 'Fixed the second menu thing.' },
                ],
                known_issues: [],
            }],
        }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.show();

        const cats = Array.from(ctx.doc.querySelectorAll('.wn-cat')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(cats.join('|'), 'Content|Changes|Fixes',
            'categories read new, then moved, then repaired -- and use headings, not type names'));

        // Menus appears twice overall (once under Changes, once under Fixes) but only
        // once within a category, even though its two fixes were not adjacent.
        const scopes = Array.from(ctx.doc.querySelectorAll('.wn-scope')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(scopes.join('|'), 'Store|Menus|Co-op|Menus',
            'each scope heads its rows once per category'));

        const items = Array.from(ctx.doc.querySelectorAll('.wn-entry li')).map(e => e.textContent);
        ctx.expect(ctx.assert.eq(items.length, 5, 'every entry still renders'));
    },
});

// Fail-closed. A missing changelog is not the player's problem, and the menu
// behind the bulletin still has to work.
TSICTestHarness.register({
    name: 'Welcome notice: a missing changelog mounts nothing',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => ({ ok: false, status: 404, json: () => Promise.resolve(null) }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.mount({ waitMs: 20 });
        await new Promise(r => setTimeout(r, 60));

        ctx.expect(ctx.assert.falsy(ctx.doc.getElementById('welcome-notice'),
            'no bulletin should be built when the fetch fails'));
    },
});

TSICTestHarness.register({
    name: 'Welcome notice: an empty release list mounts nothing',
    file: '/screens/test-welcome-notice.html',
    async run(ctx) {
        stubFetch(ctx, () => okJson({ releases: [] }));
        await ctx.doc.defaultView.TSIC.WelcomeNotice.mount({ waitMs: 20 });
        await new Promise(r => setTimeout(r, 60));

        ctx.expect(ctx.assert.falsy(ctx.doc.getElementById('welcome-notice'),
            'a changelog with no releases is as good as no changelog'));
    },
});
